parameters:
    uebb.hateoas.relation_provider.class: uebb\HateoasBundle\Service\RelationProvider
    uebb.hateoas.link_parser.class: uebb\HateoasBundle\Service\LinkParser
    uebb.hateoas.link_resolver.class: uebb\HateoasBundle\Service\LinkResolver
    uebb.hateoas.request_processor.class: uebb\HateoasBundle\Service\RequestProcessor
    uebb.hateoas.query_parser.class: uebb\HateoasBundle\Service\QueryParser
    uebb.hateoas.routing.loader.class: uebb\HateoasBundle\Routing\HateoasRouteLoader
    uebb.hateoas.permission_checker.class: uebb\HateoasBundle\EventListener\PermissionChecker
    uebb.hateoas.encoder_injector.class: uebb\HateoasBundle\EventListener\EncoderInjector
    uebb.hateoas.file_saver.class: uebb\HateoasBundle\EventListener\FileSaver
    uebb.hateoas.form_resolver.class: uebb\HateoasBundle\Service\FormResolver
    uebb.hateoas.image_resizer.class: uebb\HateoasBundle\Service\ImageResizer

services:

    uebb.hateoas.relation_provider:
        class: %uebb.hateoas.relation_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - @logger
            - @service_container
            - @security.token_storage

    uebb.hateoas.link_parser:
        class: %uebb.hateoas.link_parser.class%

    uebb.hateoas.link_resolver:
        class: %uebb.hateoas.link_resolver.class%
        arguments:
            - @controller_resolver
            - @router
            - @kernel
            - @event_dispatcher

    uebb.hateoas.request_processor:
        class: %uebb.hateoas.request_processor.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @uebb.hateoas.link_parser
            - @uebb.hateoas.link_resolver
            - @uebb.hateoas.form_resolver
            - @event_dispatcher
            - @uebb.hateoas.query_parser
            - @jms_serializer
            - @validator

    uebb.hateoas.query_parser:
        class: %uebb.hateoas.query_parser.class%
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
            - @annotation_reader

    uebb.hateoas.routing.loader:
        class: %uebb.hateoas.routing.loader.class%
        arguments:
            - @service_container
            - @file_locator
            - @controller_name_converter
            - @fos_rest.routing.loader.reader.controller
            - %fos_rest.routing.loader.default_format%
        tags:
            - {name: routing.loader }

    uebb.hateoas.permission_checker:
        class: %uebb.hateoas.permission_checker.class%
        arguments:
            - @security.authorization_checker
        tags:
            - { name: kernel.event_listener, event: uebb.hateoas.action, method:onActionEvent, priority: 250 }

    uebb.hateoas.form_resolver:
        class: %uebb.hateoas.form_resolver.class%
        arguments:
            - @form.factory
            - @annotation_reader

    uebb.hateoas.file_saver:
        class: %uebb.hateoas.file_saver.class%
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: uebb.hateoas.action_post_post, method:onPostPost }
            - { name: kernel.event_listener, event: uebb.hateoas.action_persist_remove, method:onPersistRemove }

    uebb.hateoas.encoder_injector:
        class: %uebb.hateoas.encoder_injector.class%
        arguments:
            - @security.encoder_factory
        tags:
            - { name: kernel.event_listener, event: uebb.hateoas.action, method:onActionEvent }

    uebb.hateoas.entity_voter:
        class: uebb\HateoasBundle\Security\Authorization\Voter\ResourceVoter
        abstract: true
        public: false
        calls:
            - [setRoleHierarchy, [@security.role_hierarchy]]

    uebb.hateoas.image_resizer:
        class: %uebb.hateoas.image_resizer.class%
        arguments:
            - @service_container





