parameters:


services:

    uebb.hateoas.doctrine_relation_provider:
        class: uebb\HateoasBundle\Service\DoctrineRelationProvider
        arguments: [@doctrine.orm.entity_manager, @router, @logger, @service_container]

    uebb.hateoas.link_parser:
        class: uebb\HateoasBundle\Service\LinkParser
        arguments: [@uebb.hateoas.link_resolver]

    uebb.hateoas.link_resolver:
        class: uebb\HateoasBundle\Service\LinkResolver
        arguments: [@controller_resolver, @router, @kernel, @event_dispatcher]

    uebb.hateoas.request_processor:
        class: uebb\HateoasBundle\Service\RequestProcessor
        arguments: [@doctrine.orm.entity_manager, @uebb.hateoas.link_parser, @form.factory, @event_dispatcher, @uebb.hateoas.query_parser]

    uebb.hateoas.response_processor:
        class: uebb\HateoasBundle\Service\ResponseProcessor
        arguments: [@router]

    uebb.hateoas.query_parser:
        class: uebb\HateoasBundle\Service\QueryParser
        arguments: [@service_container, @doctrine.orm.entity_manager]





